on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     stylegan2:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  StyleGan2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        pip install scipy==1.3.3
        pip install requests==2.22.0
        pip install Pillow==6.2.1
        cd /inputs/stylegan2
        apt-get install sudo -y
        
        sudo apt-get install wget
        curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
        sudo apt-get install -y nodejs
        curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run
        curl -fsSL https://code-server.dev/install.sh | sh
        npm install -g localtunnel
        code-server --bind-addr 127.0.0.1:8040 --auth none & lt --port 8040

      image: tensorflow/tensorflow:1.14.0-gpu-py3
